#!/bin/sh

# Check for backup file if does n't exist show error
# message and exit

backup="$HOME/.config/violyOS-welcome/cinnamon-backup.conf"

if [ ! -f $backup ]
then
  # echo "Backup file not found"
  exit
fi

dconf load /org/cinnamon/ < $backup

rm -f $backup

# Just give sometime for panel to restart
sleep 2
